steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/force-repo/force-storefront'
      - '-f'
      - 'Dockerfile.storefront'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'
      - '.'
    id: 'storefront-build'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'force-storefront'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/force-repo/force-storefront'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
    id: 'storefront-deploy'
    waitFor: ['storefront-build']

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/force-repo/force-storefront'

substitutions:
  _NEXT_PUBLIC_API_URL: 'https://force-api-735064695486.asia-south1.run.app'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
